name: Push Docker Image to Tencent Cloud
on:
    #schedule:
      #- cron: 0 */10 * * 5
    repository_dispatch:
    workflow_dispatch:
      inputs:
        ssh:
          description: 'SSH connection to Actions'
          required: false
          default: 'false'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v4
    
          - name: Pull Docker Image from Docker Hub
            run: docker pull xprobe/xinference:latest-cpu
    
          - name: Tag Docker Image
            run: docker tag xprobe/xinference:latest-cpu ccr.ccs.tencentyun.com/jerryliang/xin:latest-cpu
    
          - name: Log in to Tencent Cloud
            uses: docker/login-action@v3
            with:
              registry: ccr.ccs.tencentyun.com
              username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
              password: ${{ secrets.TENCENT_CLOUD_PASSWORD }}
    
          - name: Push Docker Image to Tencent Cloud
            run: docker push ccr.ccs.tencentyun.com/my-repo/xinference:latest-cpu